# Config file for automatic testing at travis-ci.org

language: python

dist: xenial

python:
  - 3.7

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
# And update pip to latest version
install:
  - python -m pip install -U pip
  - pip install -U tox-travis

# Command to run tests, e.g. python setup.py test
script: tox


